name: backend
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.12.0

# Add regular dependencies here.
dependencies:
  path: ^1.9.0
  shelf: ^1.4.1
  shelf_router: ^1.1.4
  postgres: ^3.5.11 # Upgraded to v3 to avoid using deprecated connection models
  bcrypt: ^1.2.0 # Upgraded for Dart 3+ compliance

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
